apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: spark-applications
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-applications
roleRef:
  kind: Role
  name: spark
  apiGroup: rbac.authorization.k8s.io
