apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-applications
  name: spark
rules:
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - pods
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - configmaps
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
